spring:
  datasource:
    url: jdbc:mysql://10.83.16.3:3306/milleniumfalcon?useSSL=false
    username: root
    password: x0sMfIoOGlKF85ei
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect